const attire_allowance_rates = [
    [
        {
            "assignmentType": "TEMPORARY",
            "positionGroupName": "กลุ่มพนักงานระดับ 6 ขึ้นไป",
            "positionName": "รองผู้ว่าการ,ที่ปรึกษา ผู้อำนวยการฝ่ายผู้ อ่านวยการภูมิภาค,ผู้อำนวยการสำนัก.ผู้อำนวย การกอง,ผู้อ่านวยการกลุ่ม,ผู้ช่วยผู้อำนวยการ ฝ่าย,ผู้ช่วยผู้อำนวยการภูมิภาค,ผู้ช่วยผู้อำนวย การสำนัก, ,หัวหน้า หัวหน้างาน, ผู้ช่วยผู้อำนวยการกลุ่มผู้ ช่วยผู้อำนวยการกอง,รองผู้อำนวยการกลุ่มผู้ ช่วยผู้อำนวยการสำนักงาน ททท, C6, C7, C8,C9,C10,C11,ประธาน กรรมการ,กรรมการ,ผู้ว่าการ ททท.",
            "levelCodeStart": 6,
            "levelCodeEnd": 11,
            "destinationType": "A",
            "rateThb": 9000,
            "spouseRateThb": 0,
            "childRateThb": 0,
          },
          {
            "assignmentType": "TEMPORARY",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 5 ลงมา หรือลูกจ้าง",
            "positionName": "C5, C4, C3, C2, C1\t",
            "levelCodeStart": 1,
            "levelCodeEnd": 5,
            "destinationType": "A",
            "rateThb": 7500,
            "spouseRateThb": 0,
            "childRateThb": 0,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 10 ขึ้นไป",
            "positionName": "ประธานคณะกรรมการ ททท., ผู้ว่าการ, รองผู้ว่าการ, ที่ปรึกษา, C10, C11\t",
            "levelCodeStart": 10,
            "levelCodeEnd": 11,
            "destinationType": "B",
            "rateThb": 40000,
            "spouseRateThb": 30000,
            "childRateThb": 15000,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 10 ขึ้นไป",
            "positionName": "ประธานคณะกรรมการ ททท., ผู้ว่าการ, รองผู้ว่าการ, ที่ปรึกษา, C10, C11",
            "levelCodeStart": 10,
            "levelCodeEnd": 11,
            "destinationType": "A",
            "rateThb": 60000,
            "spouseRateThb": 40000,
            "childRateThb": 18000,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 5 ลงมา",
            "positionName": "C5, C4, C3, C2, C1\t",
            "levelCodeStart": 1,
            "levelCodeEnd": 5,
            "destinationType": "B",
            "rateThb": 30000,
            "spouseRateThb": 18000,
            "childRateThb": 9000,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 6 จนถึงระดับ 9",
            "positionName": "ที่ปรึกษา, ผู้อำนวยการฝ่าย, ผู้อำนวยการภูมิภาค, ผู้อำนวยการสำนัก, ผู้อำนวยการกอง, ผู้อำนวยการกลุ่ม, ผู้ช่วยผู้อำนวยการฝ่าย, ผู้ช่วยผู้อ่านวยการภูมิภาค, ผู้ช่วยผู้อำนวยการสำนัก, หัวหน้างาน, ผู้ช่วยผู้อำนวยการกลุ่ม, ผู้ช่วยผู้อำนวยการกอง, ผู้อำนวยการสำนักงาน ททท. ผู้ช่วยผู้อ่านวยการสำนักงาน ททท., C6, C7 ,C8, C9,",
            "levelCodeStart": 6,
            "levelCodeEnd": 9,
            "destinationType": "A",
            "rateThb": 45000,
            "spouseRateThb": 30000,
            "childRateThb": 15000,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "พนักงานซึ่งดำรงตำแหน่งตั้งแต่ระดับ 5 ลงมา",
            "positionName": "C5, C4, C3, C2, C1",
            "levelCodeStart": 1,
            "levelCodeEnd": 5,
            "destinationType": "A",
            "rateThb": 40000,
            "spouseRateThb": 25000,
            "childRateThb": 14000,
          },
          {
            "assignmentType": "PERMANENT",
            "positionGroupName": "กลุ่มพนักงานระดับ 6-9 และตำแหน่งบริหารบางส่วน",
            "positionName": "ผู้อ่านวยการฝ่าย, ผู้อำนวยการภูมิภาค, ผู้อ่านวยการสำนัก, ผู้อำนวยการกอง, ผู้อำนวยการกลุ่ม, ผู้ช่วยผู้อำนวยการฝ่าย, ผู้ช่วยผู้อำนวยการภูมิภาค, ผู้ช่วยผู้อำนวยการสำนัก, หัวหน้างาน, ผู้ช่วยผู้อ่านวยการกลุ่ม, ผู้ช่วยผู้อำนวยการกอง, ผู้อ่านวยการสำนักงาน ททท., ผู้ช่วยผู้อ่านวยการสำนักงาน ททท., C6, C7, C8, C9",
            "levelCodeStart": 6,
            "levelCodeEnd": 9,
            "destinationType": "B",
            "rateThb": 35000,
            "spouseRateThb": 20000,
            "childRateThb": 10000,
          }
      ]
    ]

module.exports = attire_allowance_rates;