const countries = [
    { id: 1, code: "AD", name_en: "ANDORRA", name_th: "ประเทศอันดอร์รา", type: "A", percent_increase: 0 },
    { id: 2, code: "AE", name_en: "UNITED ARAB EMIRATES", name_th: "สหรัฐอาหรับเอมิเรตส์", type: "A", percent_increase: 0 },
    { id: 3, code: "AF", name_en: "AFGHANISTAN", name_th: "ประเทศอัฟกานิสถาน", type: null, percent_increase: 0 },
    { id: 4, code: "AG", name_en: "ANTIGUA AND BARBUDA", name_th: "ประเทศแอนติกาและบาร์บูดา", type: null, percent_increase: 0 },
    { id: 5, code: "AI", name_en: "ANGUILLA", name_th: "ประเทศแองกวิลลา", type: null, percent_increase: 0 },
    { id: 6, code: "AL", name_en: "ALBANIA", name_th: "ประเทศแอลเบเนีย", type: null, percent_increase: 0 },
    { id: 7, code: "AM", name_en: "ARMENIA", name_th: "ประเทศอาร์มีเนีย", type: "B", percent_increase: 0 },
    { id: 8, code: "AO", name_en: "ANGOLA", name_th: "ประเทศแองโกลา", type: null, percent_increase: 0 },
    { id: 9, code: "AQ", name_en: "ANTARCTICA", name_th: "ประเทศแอนตาร์กติกา", type: null, percent_increase: 0 },
    { id: 10, code: "AR", name_en: "ARGENTINA", name_th: "ประเทศอาร์เจนตินา", type: "B", percent_increase: 0 },
    { id: 11, code: "AS", name_en: "AMERICAN SAMOA", name_th: "ประเทศอเมริกันซามัว", type: null, percent_increase: 0 },
    { id: 12, code: "AT", name_en: "AUSTRIA", name_th: "ประเทศออสเตรีย", type: "A", percent_increase: 0 },
    { id: 13, code: "AU", name_en: "AUSTRALIA", name_th: "ประเทศออสเตรเลีย", type: "A", percent_increase: 0 },
    { id: 14, code: "AW", name_en: "ARUBA", name_th: "ประเทศอารูบา", type: null, percent_increase: 0 },
    { id: 15, code: "AX", name_en: "ALAND ISLANDS", name_th: "ประเทศหมู่เกาะโอลันด์", type: null, percent_increase: 0 },
    { id: 16, code: "AZ", name_en: "AZERBAIJAN", name_th: "ประเทศอาเซอร์ไบจาน", type: "A", percent_increase: 0 },
    { id: 17, code: "BA", name_en: "BOSNIA AND HERZEGOVINA", name_th: "ประเทศบอสเนียและเฮอร์เซโกวีนา", type: "A", percent_increase: 0 },
    { id: 18, code: "BB", name_en: "BARBADOS", name_th: "ประเทศบาร์เบโดส", type: null, percent_increase: 0 },
    { id: 19, code: "BD", name_en: "BANGLADESH", name_th: "ประเทศบังกลาเทศ", type: "B", percent_increase: 0 },
    { id: 20, code: "BE", name_en: "BELGIUM", name_th: "ประเทศเบลเยียม", type: "A", percent_increase: 25 },
    { id: 21, code: "BF", name_en: "BURKINA FASO", name_th: "ประเทศบูร์กินาฟาโซ", type: null, percent_increase: 0 },
    { id: 22, code: "BG", name_en: "BULGARIA", name_th: "ประเทศบัลแกเรีย", type: "A", percent_increase: 0 },
    { id: 23, code: "BH", name_en: "BAHRAIN", name_th: "ประเทศบาห์เรน", type: "B", percent_increase: 0 },
    { id: 24, code: "BI", name_en: "BURUNDI", name_th: "ประเทศบุรุนดี", type: "B", percent_increase: 0 },
    { id: 25, code: "BJ", name_en: "BENIN", name_th: "ประเทศเบนิน", type: "B", percent_increase: 0 },
    { id: 26, code: "BL", name_en: "SAINT BARTHELEMY", name_th: "ประเทศแซงบาร์เตเลมี", type: null, percent_increase: 0 },
    { id: 27, code: "BM", name_en: "BERMUDA", name_th: "ประเทศเบอร์มิวดา", type: null, percent_increase: 0 },
    { id: 28, code: "BN", name_en: "BRUNEI DARUSSALAM", name_th: "ประเทศบรูไน", type: "B", percent_increase: 0 },
    { id: 29, code: "BO", name_en: "BOLIVIA", name_th: "ประเทศโบลิเวีย", type: null, percent_increase: 0 },
    { id: 30, code: "BQ", name_en: "BONAIRE,SAINT EUSTATIUS AND SABA", name_th: "ประเทศเนเธอร์แลนด์แคริบเบียน", type: null, percent_increase: 0 },
    { id: 31, code: "BR", name_en: "BRAZIL", name_th: "ประเทศบราซิล", type: "A", percent_increase: 0 },
    { id: 32, code: "BS", name_en: "BAHAMAS", name_th: "ประเทศบาฮามาส", type: "B", percent_increase: 0 },
    { id: 33, code: "BT", name_en: "BHUTAN", name_th: "ประเทศภูฏาน", type: "B", percent_increase: 0 },
    { id: 34, code: "BV", name_en: "BOUVET ISLAND", name_th: "ประเทศเกาะบูเวต์", type: null, percent_increase: 0 },
    { id: 35, code: "BW", name_en: "BOTSWANA", name_th: "ประเทศบอตสวานา", type: null, percent_increase: 0 },
    { id: 36, code: "BY", name_en: "BELARUS", name_th: "ประเทศเบลารุส", type: "B", percent_increase: 0 },
    { id: 37, code: "BZ", name_en: "BELIZE", name_th: "ประเทศเบลีซ", type: null, percent_increase: 0 },
    { id: 38, code: "CA", name_en: "CANADA", name_th: "ประเทศแคนาดา", type: "A", percent_increase: 0 },
    { id: 39, code: "CC", name_en: "COCOS (KEELING) ISLANDS", name_th: "ประเทศหมู่เกาะโคโคส", type: null, percent_increase: 0 },
    { id: 40, code: "CD", name_en: "CONGO, THE DEMOCRATIC REPUBLIC OF T", name_th: "สาธารณรัฐประชาธิปไตยคองโก", type: null, percent_increase: 0 },
    { id: 41, code: "CF", name_en: "CENTRAL AFRICAN REPUBLIC", name_th: "สาธารณรัฐแอฟริกากลาง", type: "B", percent_increase: 0 },
    { id: 42, code: "CG", name_en: "CONGO", name_th: "สาธารณรัฐคองโก", type: null, percent_increase: 0 },
    { id: 43, code: "CH", name_en: "SWITZERLAND", name_th: "ประเทศสวิตเซอร์แลนด์", type: "A", percent_increase: 40 },
    { id: 44, code: "CI", name_en: "COTE D IVOIRE", name_th: "ประเทศโกตดิวัวร์", type: "B", percent_increase: 0 },
    { id: 45, code: "CK", name_en: "COOK ISLANDS", name_th: "ประเทศหมู่เกาะคุก", type: null, percent_increase: 0 },
    { id: 46, code: "CL", name_en: "CHILE", name_th: "ประเทศชิลี", type: "A", percent_increase: 0 },
    { id: 47, code: "CM", name_en: "CAMEROON", name_th: "ประเทศแคเมอรูน", type: "B", percent_increase: 0 },
    { id: 48, code: "CN", name_en: "CHINA", name_th: "ประเทศจีน", type: "A", percent_increase: 0 },
    { id: 49, code: "CO", name_en: "COLOMBIA", name_th: "ประเทศโคลอมเบีย", type: null, percent_increase: 0 },
    { id: 50, code: "CR", name_en: "COSTA RICA", name_th: "ประเทศคอสตาริกา", type: "B", percent_increase: 0 },
    { id: 51, code: "CU", name_en: "CUBA", name_th: "ประเทศคิวบา", type: null, percent_increase: 0 },
    { id: 52, code: "CV", name_en: "CAPE VERDE", name_th: "ประเทศกาบูเวร์ดี", type: null, percent_increase: 0 },
    { id: 53, code: "CW", name_en: "CURACAO", name_th: "ประเทศกือราเซา", type: null, percent_increase: 0 },
    { id: 54, code: "CX", name_en: "CHRISTMAS ISLAND", name_th: "ประเทศเกาะคริสต์มาส", type: null, percent_increase: 0 },
    { id: 55, code: "CY", name_en: "CYPRUS", name_th: "ประเทศไซปรัส", type: "B", percent_increase: 0 },
    { id: 56, code: "CZ", name_en: "CZECH REPUBLIC", name_th: "สาธารณรัฐเช็ก", type: "A", percent_increase: 0 },
    { id: 57, code: "DE", name_en: "GERMANY", name_th: "ประเทศเยอรมนี", type: "A", percent_increase: 25 },
    { id: 58, code: "DJ", name_en: "DJIBOUTI", name_th: "ประเทศจิบูตี", type: "B", percent_increase: 0 },
    { id: 59, code: "DK", name_en: "DENMARK", name_th: "ประเทศเดนมาร์ก", type: "A", percent_increase: 0 },
    { id: 60, code: "DM", name_en: "DOMINICA", name_th: "ประเทศดอมินีกา", type: null, percent_increase: 0 },
    { id: 61, code: "DO", name_en: "DOMINICAN REPUBLIC", name_th: "สาธารณรัฐโดมินิกัน", type: null, percent_increase: 0 },
    { id: 62, code: "DZ", name_en: "ALGERIA", name_th: "ประเทศแอลจีเรีย", type: "A", percent_increase: 0 },
    { id: 63, code: "EC", name_en: "ECUADOR", name_th: "ประเทศเอกวาดอร์", type: null, percent_increase: 0 },
    { id: 64, code: "EE", name_en: "ESTONIA", name_th: "ประเทศเอสโตเนีย", type: "A", percent_increase: 0 },
    { id: 65, code: "EG", name_en: "EGYPT", name_th: "ประเทศอียิปต์", type: "B", percent_increase: 0 },
    { id: 66, code: "EH", name_en: "WESTERN SAHARA", name_th: "ประเทศซาฮาราตะวันตก", type: null, percent_increase: 0 },
    { id: 67, code: "ER", name_en: "ERITREA", name_th: "ประเทศเอริเทรีย", type: null, percent_increase: 0 },
    { id: 68, code: "ES", name_en: "SPAIN", name_th: "ประเทศสเปน", type: "A", percent_increase: 25 },
    { id: 69, code: "ET", name_en: "ETHIOPIA", name_th: "ประเทศเอธิโอเปีย", type: null, percent_increase: 0 },
    { id: 70, code: "FI", name_en: "FINLAND", name_th: "ประเทศฟินแลนด์", type: "A", percent_increase: 0 },
    { id: 71, code: "FJ", name_en: "FIJI", name_th: "ประเทศฟีจี", type: null, percent_increase: 0 },
    { id: 72, code: "FK", name_en: "FALKLAND ISLANDS (MALVINAS)", name_th: "ประเทศหมู่เกาะฟอล์กแลนด์", type: null, percent_increase: 0 },
    { id: 73, code: "FM", name_en: "MICRONESIA (FEDERATED STATES OF)", name_th: "ประเทศไมโครนีเซีย", type: null, percent_increase: 0 },
    { id: 74, code: "FO", name_en: "FAROE ISLANDS", name_th: "ประเทศหมู่เกาะแฟโร", type: null, percent_increase: 0 },
    { id: 75, code: "FR", name_en: "FRANCE", name_th: "ประเทศฝรั่งเศส", type: "A", percent_increase: 40 },
    { id: 76, code: "GA", name_en: "GABON", name_th: "ประเทศกาบอง", type: null, percent_increase: 0 },
    { id: 77, code: "GB", name_en: "UNITED KINGDOM", name_th: "สหราชอาณาจักร", type: "A", percent_increase: 25 },
    { id: 78, code: "GD", name_en: "GRENADA", name_th: "ประเทศเกรเนดา", type: null, percent_increase: 0 },
    { id: 79, code: "GE", name_en: "GEORGIA", name_th: "ประเทศจอร์เจีย", type: "B", percent_increase: 0 },
    { id: 80, code: "GF", name_en: "FRENCE GUIANA", name_th: "ประเทศเฟรนช์เกียนา", type: null, percent_increase: 0 },
    { id: 81, code: "GG", name_en: "GUERNSEY", name_th: "ประเทศเกิร์นซีย์", type: null, percent_increase: 0 },
    { id: 82, code: "GH", name_en: "GHANA", name_th: "ประเทศกานา", type: "B", percent_increase: 0 },
    { id: 83, code: "GI", name_en: "GIBRALTAR", name_th: "ประเทศยิบรอลตาร์", type: null, percent_increase: 0 },
    { id: 84, code: "GL", name_en: "GREENLAND", name_th: "ประเทศกรีนแลนด์", type: null, percent_increase: 0 },
    { id: 85, code: "GM", name_en: "GAMBIA", name_th: "ประเทศแกมเบีย", type: "B", percent_increase: 0 },
    { id: 86, code: "GN", name_en: "GUINEA", name_th: "ประเทศกินี", type: null, percent_increase: 0 },
    { id: 87, code: "GP", name_en: "GUADELOUPE", name_th: "ประเทศกัวเดอลุป", type: null, percent_increase: 0 },
    { id: 88, code: "GQ", name_en: "EQUATORIAL GUINEA", name_th: "ประเทศอิเควทอเรียลกินี", type: null, percent_increase: 0 },
    { id: 89, code: "GR", name_en: "GREECE", name_th: "ประเทศกรีซ", type: "A", percent_increase: 0 },
    { id: 90, code: "GS", name_en: "SOUTH GEORGIA AND THE SOUTH SANDWIC", name_th: "ประเทศเกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช", type: null, percent_increase: 0 },
    { id: 91, code: "GT", name_en: "GUATEMALA", name_th: "ประเทศกัวเตมาลา", type: null, percent_increase: 0 },
    { id: 92, code: "GU", name_en: "GUAM", name_th: "ประเทศกวม", type: null, percent_increase: 0 },
    { id: 93, code: "GW", name_en: "GUINEA-BISSAU", name_th: "ประเทศกินี-บิสเซา", type: null, percent_increase: 0 },
    { id: 94, code: "GY", name_en: "GUYANA", name_th: "ประเทศกายอานา", type: null, percent_increase: 0 },
    { id: 95, code: "HK", name_en: "HONG KONG", name_th: "ประเทศฮ่องกง", type: "A", percent_increase: 0 },
    { id: 96, code: "HM", name_en: "HEARD ISLAND AND MCDONALD ISLANDS", name_th: "ประเทศเกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์", type: null, percent_increase: 0 },
    { id: 97, code: "HN", name_en: "HONDURAS", name_th: "ประเทศฮอนดูรัส", type: null, percent_increase: 0 },
    { id: 98, code: "HR", name_en: "CROATIA", name_th: "ประเทศโครเอเชีย", type: "A", percent_increase: 0 },
    { id: 99, code: "HT", name_en: "HAITI", name_th: "ประเทศเฮติ", type: null, percent_increase: 0 },
    { id: 100, code: "HU", name_en: "HUNGARY", name_th: "ประเทศฮังการี", type: "A", percent_increase: 0 },
    { id: 101, code: "ID", name_en: "INDONESIA", name_th: "ประเทศอินโดนีเซีย", type: "A", percent_increase: 0 },
    { id: 102, code: "IE", name_en: "IRELAND", name_th: "ประเทศไอร์แลนด์", type: "A", percent_increase: 0 },
    { id: 103, code: "IL", name_en: "ISRAEL", name_th: "ประเทศอิสราเอล", type: "B", percent_increase: 0 },
    { id: 104, code: "IM", name_en: "ISLE OF MAN", name_th: "ประเทศไอล์ออฟแมน", type: null, percent_increase: 0 },
    { id: 105, code: "IN", name_en: "INDIA", name_th: "ประเทศอินเดีย", type: "A", percent_increase: 0 },
    { id: 106, code: "IO", name_en: "BRITISH INDIAN OCEAN TERRITORY", name_th: "ประเทศบริติชอินเดียนโอเชียนเทร์ริทอรี", type: null, percent_increase: 0 },
    { id: 107, code: "IQ", name_en: "IRAQ", name_th: "ประเทศอิรัก", type: "B", percent_increase: 0 },
    { id: 108, code: "IR", name_en: "IRAN (ISLAMIC REPUBLIC OF)", name_th: "ประเทศอิหร่าน", type: "B", percent_increase: 0 },
    { id: 109, code: "IS", name_en: "ICELAND", name_th: "ประเทศไอซ์แลนด์", type: "A", percent_increase: 0 },
    { id: 110, code: "IT", name_en: "ITALY", name_th: "ประเทศอิตาลี", type: "A", percent_increase: 40 },
    { id: 111, code: "JE", name_en: "JERSEY", name_th: "ประเทศเจอร์ซีย์", type: null, percent_increase: 0 },
    { id: 112, code: "JM", name_en: "JAMAICA", name_th: "ประเทศจาเมกา", type: "B", percent_increase: 0 },
    { id: 113, code: "JO", name_en: "JORDAN", name_th: "ประเทศจอร์แดน", type: "B", percent_increase: 0 },
    { id: 114, code: "JP", name_en: "JAPAN", name_th: "ประเทศญี่ปุ่น", type: "A", percent_increase: 40 },
    { id: 115, code: "KE", name_en: "KENYA", name_th: "ประเทศเคนยา", type: "B", percent_increase: 0 },
    { id: 116, code: "KG", name_en: "KYRGYZSTAN", name_th: "ประเทศคีร์กีซสถาน", type: "B", percent_increase: 0 },
    { id: 117, code: "KH", name_en: "CAMBODIA", name_th: "ประเทศกัมพูชา", type: "A", percent_increase: 0 },
    { id: 118, code: "KI", name_en: "KIRIBATI", name_th: "ประเทศคิริบาส", type: null, percent_increase: 0 },
    { id: 119, code: "KM", name_en: "COMOROS", name_th: "ประเทศคอโมโรส", type: null, percent_increase: 0 },
    { id: 120, code: "KN", name_en: "SAINT KITTS AND NEVIS", name_th: "ประเทศเซนต์คิตส์และเนวิส", type: null, percent_increase: 0 },
    { id: 121, code: "KP", name_en: "KOREA DPR", name_th: "ประเทศเกาหลีเหนือ", type: null, percent_increase: 0 },
    { id: 122, code: "KR", name_en: "KOREA,REPUBLIC OF", name_th: "ประเทศเกาหลีใต้", type: "A", percent_increase: 0 },
    { id: 123, code: "KW", name_en: "KUWAIT", name_th: "ประเทศคูเวต", type: "B", percent_increase: 0 },
    { id: 124, code: "KY", name_en: "CAYMAN ISLANDS", name_th: "ประเทศหมู่เกาะเคย์แมน", type: null, percent_increase: 0 },
    { id: 125, code: "KZ", name_en: "KAZAKHSTAN", name_th: "ประเทศคาซัคสถาน", type: "B", percent_increase: 0 },
    { id: 126, code: "LA", name_en: "LAO PDR", name_th: "ประเทศลาว", type: null, percent_increase: 0 },
    { id: 127, code: "LB", name_en: "LEBANON", name_th: "ประเทศเลบานอน", type: null, percent_increase: 0 },
    { id: 128, code: "LC", name_en: "SAINT LUCIA", name_th: "ประเทศเซนต์ลูเชีย", type: null, percent_increase: 0 },
    { id: 129, code: "LI", name_en: "LIECHTENSTEIN", name_th: "ประเทศลิกเตนสไตน์", type: null, percent_increase: 0 },
    { id: 130, code: "LK", name_en: "SRI LANKA", name_th: "ประเทศศรีลังกา", type: "B", percent_increase: 0 },
    { id: 131, code: "LR", name_en: "LIBERIA", name_th: "ประเทศไลบีเรีย", type: null, percent_increase: 0 },
    { id: 132, code: "LS", name_en: "LESOTHO", name_th: "ประเทศเลโซโท", type: null, percent_increase: 0 },
    { id: 133, code: "LT", name_en: "LITHUANIA", name_th: "ประเทศลิทัวเนีย", type: "A", percent_increase: 0 },
    { id: 134, code: "LU", name_en: "LUXEMBOURG", name_th: "ประเทศลักเซมเบิร์ก", type: "A", percent_increase: 0 },
    { id: 135, code: "LV", name_en: "LATVIA", name_th: "ประเทศลัตเวีย", type: "B", percent_increase: 0 },
    { id: 136, code: "LY", name_en: "LIBYAN ARAB JAMAHIRIYA", name_th: "ประเทศลิเบีย", type: null, percent_increase: 0 },
    { id: 137, code: "MA", name_en: "MOROCCO", name_th: "ประเทศโมร็อกโก", type: "A", percent_increase: 0 },
    { id: 138, code: "MC", name_en: "MONACO", name_th: "ประเทศโมนาโก", type: "A", percent_increase: 0 },
    { id: 139, code: "MD", name_en: "MOLDOVA REPUBLIC OF", name_th: "ประเทศมอลโดวา", type: "B", percent_increase: 0 },
    { id: 140, code: "ME", name_en: "MONTENEGRO", name_th: "ประเทศมอนเตเนโกร", type: null, percent_increase: 0 },
    { id: 141, code: "MF", name_en: "SAINT MARTIN (FRENCH PART)", name_th: "ประเทศแซงมาร์แตง", type: null, percent_increase: 0 },
    { id: 142, code: "MG", name_en: "MADAGASCAR", name_th: "ประเทศมาดากัสการ์", type: null, percent_increase: 0 },
    { id: 143, code: "MH", name_en: "MARSHALL ISLAND", name_th: "ประเทศหมู่เกาะมาร์แชลล์", type: null, percent_increase: 0 },
    { id: 144, code: "MK", name_en: "THE REPUBLIC OF NORTH MACEDONIA", name_th: "ประเทศนอร์ทมาซิโดเนีย", type: "B", percent_increase: 0 },
    { id: 145, code: "ML", name_en: "MALI", name_th: "ประเทศมาลี", type: "B", percent_increase: 0 },
    { id: 146, code: "MM", name_en: "MYANMAR", name_th: "ประเทศพม่า", type: "B", percent_increase: 0 },
    { id: 147, code: "MN", name_en: "MONGOLIA", name_th: "ประเทศมองโกเลีย", type: null, percent_increase: 0 },
    { id: 148, code: "MO", name_en: "MACAU", name_th: "ประเทศมาเก๊า", type: null, percent_increase: 0 },
    { id: 149, code: "MP", name_en: "NORTHERN MARIANA ISLANDS", name_th: "ประเทศหมู่เกาะนอร์เทิร์นมาเรียนา", type: null, percent_increase: 0 },
    { id: 150, code: "MQ", name_en: "MARTINIQUE", name_th: "ประเทศมาร์ตีนิก", type: null, percent_increase: 0 },
    { id: 151, code: "MR", name_en: "MAURITANIA", name_th: "ประเทศมอริเตเนีย", type: "B", percent_increase: 0 },
    { id: 152, code: "MS", name_en: "MONTSERRAT", name_th: "ประเทศมอนต์เซอร์รัต", type: null, percent_increase: 0 },
    { id: 153, code: "MT", name_en: "MALTA", name_th: "ประเทศมอลตา", type: "A", percent_increase: 0 },
    { id: 154, code: "MU", name_en: "MAURITIUS", name_th: "ประเทศมอริเชียส", type: "A", percent_increase: 0 },
    { id: 155, code: "MV", name_en: "MALDIVES", name_th: "ประเทศมัลดีฟส์", type: null, percent_increase: 0 },
    { id: 156, code: "MW", name_en: "MALAWI", name_th: "ประเทศมาลาวี", type: null, percent_increase: 0 },
    { id: 157, code: "MX", name_en: "MEXICO", name_th: "ประเทศเม็กซิโก", type: "B", percent_increase: 0 },
    { id: 158, code: "MY", name_en: "MALAYSIA", name_th: "ประเทศมาเลเซีย", type: "A", percent_increase: 0 },
    { id: 159, code: "MZ", name_en: "MOZAMBIQUE", name_th: "ประเทศโมซัมบิก", type: "A", percent_increase: 0 },
    { id: 160, code: "NA", name_en: "NAMIBIA", name_th: "ประเทศนามิเบีย", type: null, percent_increase: 0 },
    { id: 161, code: "NC", name_en: "NEW CALEDONIA", name_th: "ประเทศนิวแคลิโดเนีย", type: null, percent_increase: 0 },
    { id: 162, code: "NE", name_en: "NIGER", name_th: "ประเทศไนเจอร์", type: "B", percent_increase: 0 },
    { id: 163, code: "NF", name_en: "NORFOLK ISLAND", name_th: "ประเทศเกาะนอร์ฟอล์ก", type: null, percent_increase: 0 },
    { id: 164, code: "NG", name_en: "NIGERIA", name_th: "ประเทศไนจีเรีย", type: "B", percent_increase: 0 },
    { id: 165, code: "NI", name_en: "NICARAGUA", name_th: "ประเทศนิการากัว", type: null, percent_increase: 0 },
    { id: 166, code: "NL", name_en: "NETHERLANDS", name_th: "ประเทศเนเธอร์แลนด์", type: "A", percent_increase: 0 },
    { id: 167, code: "NO", name_en: "NORWAY", name_th: "ประเทศนอร์เวย์", type: "A", percent_increase: 0 },
    { id: 168, code: "NP", name_en: "NEPAL", name_th: "ประเทศเนปาล", type: "B", percent_increase: 0 },
    { id: 169, code: "NR", name_en: "NAURU", name_th: "ประเทศนาอูรู", type: null, percent_increase: 0 },
    { id: 170, code: "NU", name_en: "NIUE", name_th: "ประเทศนีวเว", type: null, percent_increase: 0 },
    { id: 171, code: "NZ", name_en: "NEW ZEALAND", name_th: "ประเทศนิวซีแลนด์", type: "A", percent_increase: 0 },
    { id: 172, code: "OM", name_en: "OMAN", name_th: "ประเทศโอมาน", type: "A", percent_increase: 0 },
    { id: 173, code: "PA", name_en: "PANAMA", name_th: "ประเทศปานามา", type: "B", percent_increase: 0 },
    { id: 174, code: "PE", name_en: "PERU", name_th: "ประเทศเปรู", type: "A", percent_increase: 0 },
    { id: 175, code: "PF", name_en: "FRENCH POLYNESIA", name_th: "ประเทศเฟรนช์พอลินีเชีย", type: null, percent_increase: 0 },
    { id: 176, code: "PG", name_en: "PAPUA NEW GUINEA", name_th: "ประเทศปาปัวนิวกินี", type: "A", percent_increase: 0 },
    { id: 177, code: "PH", name_en: "PHILIPPINES", name_th: "ประเทศฟิลิปปินส์", type: "A", percent_increase: 0 },
    { id: 178, code: "PK", name_en: "PAKISTAN", name_th: "ประเทศปากีสถาน", type: "B", percent_increase: 0 },
    { id: 179, code: "PL", name_en: "POLAND", name_th: "ประเทศโปแลนด์", type: "A", percent_increase: 0 },
    { id: 180, code: "PM", name_en: "SAINT PIERRE AND MIQUELON", name_th: "ประเทศแซงปีแยร์และมีเกอลง", type: null, percent_increase: 0 },
    { id: 181, code: "PN", name_en: "PITCAIRN", name_th: "ประเทศหมู่เกาะพิตแคร์น", type: null, percent_increase: 0 },
    { id: 182, code: "PR", name_en: "PUERTO RICO", name_th: "ประเทศปวยร์โตรีโก", type: null, percent_increase: 0 },
    { id: 183, code: "PS", name_en: "PALESTINIAN TERRITORY, OCCUPIED", name_th: "ประเทศปาเลสไตน์", type: null, percent_increase: 0 },
    { id: 184, code: "PT", name_en: "PORTUGAL", name_th: "ประเทศโปรตุเกส", type: "A", percent_increase: 25 },
    { id: 185, code: "PW", name_en: "PALAU", name_th: "ประเทศปาเลา", type: null, percent_increase: 0 },
    { id: 186, code: "PY", name_en: "PARAGUAY", name_th: "ประเทศปารากวัย", type: null, percent_increase: 0 },
    { id: 187, code: "QA", name_en: "QATAR", name_th: "ประเทศกาตาร์", type: "B", percent_increase: 0 },
    { id: 188, code: "RE", name_en: "REUNION", name_th: "ประเทศเรอูว์นียง", type: null, percent_increase: 0 },
    { id: 189, code: "RO", name_en: "ROMANIA", name_th: "ประเทศโรมาเนีย", type: "A", percent_increase: 0 },
    { id: 190, code: "RS", name_en: "SERBIA", name_th: "ประเทศเซอร์เบีย", type: null, percent_increase: 0 },
    { id: 191, code: "RU", name_en: "RUSSIAN FEDERATION", name_th: "ประเทศรัสเซีย", type: "A", percent_increase: 40 },
    { id: 192, code: "RW", name_en: "RWANDA", name_th: "ประเทศรวันดา", type: null, percent_increase: 0 },
    { id: 193, code: "SA", name_en: "SAUDI ARABIA", name_th: "ประเทศซาอุดีอาระเบีย", type: "B", percent_increase: 0 },
    { id: 194, code: "SB", name_en: "SOLOMON ISLANDS", name_th: "ประเทศหมู่เกาะโซโลมอน", type: null, percent_increase: 0 },
    { id: 195, code: "SC", name_en: "SEYCHELLES", name_th: "ประเทศเซเชลส์", type: null, percent_increase: 0 },
    { id: 196, code: "SD", name_en: "SUDAN", name_th: "ประเทศซูดาน", type: null, percent_increase: 0 },
    { id: 197, code: "SE", name_en: "SWEDEN", name_th: "ประเทศสวีเดน", type: "A", percent_increase: 0 },
    { id: 198, code: "SG", name_en: "SINGAPORE", name_th: "ประเทศสิงคโปร์", type: "A", percent_increase: 25 },
    { id: 199, code: "SH", name_en: "SAINT HELENA", name_th: "ประเทศเซนต์เฮเลนา", type: null, percent_increase: 0 },
    { id: 200, code: "SI", name_en: "SLOVENIA", name_th: "ประเทศสโลวีเนีย", type: "A", percent_increase: 0 },
    { id: 201, code: "SJ", name_en: "SVALBARD AND JAN MAYEN", name_th: "ประเทศสฟาลบาร์และยานไมเอน", type: null, percent_increase: 0 },
    { id: 202, code: "SK", name_en: "SLOVAKIA", name_th: "ประเทศสโลวาเกีย", type: "A", percent_increase: 0 },
    { id: 203, code: "SL", name_en: "SIERRA LEONE", name_th: "ประเทศเซียร์ราลีโอน", type: "B", percent_increase: 0 },
    { id: 204, code: "SM", name_en: "SAN MARINO", name_th: "ประเทศซานมารีโน", type: null, percent_increase: 0 },
    { id: 205, code: "SN", name_en: "SENEGAL", name_th: "ประเทศเซเนกัล", type: "B", percent_increase: 0 },
    { id: 206, code: "SO", name_en: "SOMALIA", name_th: "ประเทศโซมาเลีย", type: null, percent_increase: 0 },
    { id: 207, code: "SR", name_en: "SURINAME", name_th: "ประเทศซูรินาม", type: null, percent_increase: 0 },
    { id: 208, code: "SS", name_en: "SOUTH SUDAN", name_th: "ประเทศซูดานใต้", type: null, percent_increase: 0 },
    { id: 209, code: "ST", name_en: "SAO TOME AND PRINCIPE", name_th: "ประเทศเซาตูเมและปรินซีปี", type: null, percent_increase: 0 },
    { id: 210, code: "SV", name_en: "EL SALVADOR", name_th: "ประเทศเอลซัลวาดอร์", type: null, percent_increase: 0 },
    { id: 211, code: "SX", name_en: "SINT MAARTEN", name_th: "ประเทศซินต์มาร์เติน", type: null, percent_increase: 0 },
    { id: 212, code: "SY", name_en: "SYRIAN ARAB REPUBLIC", name_th: "ประเทศซีเรีย", type: "B", percent_increase: 0 },
    { id: 213, code: "SZ", name_en: "ESWATINI", name_th: "ประเทศสวาซิแลนด์", type: "A", percent_increase: 0 },
    { id: 214, code: "TC", name_en: "TURKS AND CAICOS ISLANDS", name_th: "ประเทศหมู่เกาะเติกส์และเคคอส", type: null, percent_increase: 0 },
    { id: 215, code: "TD", name_en: "CHAD", name_th: "ประเทศชาด", type: "B", percent_increase: 0 },
    { id: 216, code: "TF", name_en: "FRENCH SOUTHERN TERRITORIES", name_th: "ประเทศเฟรนช์เซาเทิร์นและแอนตาร์กติกแลนดส์", type: null, percent_increase: 0 },
    { id: 217, code: "TG", name_en: "TOGO", name_th: "ประเทศโตโก", type: null, percent_increase: 0 },
    { id: 218, code: "TH", name_en: "THAILAND", name_th: "ประเทศไทย", type: null, percent_increase: 0 },
    { id: 219, code: "TJ", name_en: "TAJIKISTAN", name_th: "ประเทศทาจิกิสถาน", type: "B", percent_increase: 0 },
    { id: 220, code: "TK", name_en: "TOKELAU", name_th: "ประเทศโทเคอเลา", type: null, percent_increase: 0 },
    { id: 221, code: "TL", name_en: "TIMOR-LESTE", name_th: "ประเทศติมอร์-เลสเต", type: "A", percent_increase: 0 },
    { id: 222, code: "TM", name_en: "TURKMENISTAN", name_th: "ประเทศเติร์กเมนิสถาน", type: "A", percent_increase: 0 },
    { id: 223, code: "TN", name_en: "TUNISIA", name_th: "ประเทศตูนิเซีย", type: "B", percent_increase: 0 },
    { id: 224, code: "TO", name_en: "TONGA", name_th: "ประเทศตองงา", type: "B", percent_increase: 0 },
    { id: 225, code: "TR", name_en: "TURKIYE", name_th: "ประเทศตุรกี", type: "A", percent_increase: 0 },
    { id: 226, code: "TT", name_en: "TRINIDAD AND TOBAGO", name_th: "ประเทศตรินิแดดและโตเบโก", type: "B", percent_increase: 0 },
    { id: 227, code: "TV", name_en: "TUVALU", name_th: "ประเทศตูวาลู", type: null, percent_increase: 0 },
    { id: 228, code: "TW", name_en: "TAIWAN, PROVINCE OF CHINA", name_th: "ประเทศไต้หวัน", type: "A", percent_increase: 0 },
    { id: 229, code: "TZ", name_en: "TANZANIA UNITED REPUBLIC OF", name_th: "ประเทศแทนซาเนีย", type: "B", percent_increase: 0 },
    { id: 230, code: "UA", name_en: "UKRAINE", name_th: "ประเทศยูเครน", type: "B", percent_increase: 0 },
    { id: 231, code: "UG", name_en: "UGANDA", name_th: "ประเทศยูกันดา", type: "B", percent_increase: 0 },
    { id: 232, code: "UM", name_en: "UNITED STATES MINOR OUTLYING ISLAND", name_th: "ประเทศเกาะเล็กรอบนอกของสหรัฐอเมริกา", type: null, percent_increase: 0 },
    { id: 233, code: "US", name_en: "UNITED STATES", name_th: "สหรัฐ", type: "A", percent_increase: 25 },
    { id: 234, code: "UY", name_en: "URUGUAY", name_th: "ประเทศอุรุกวัย", type: null, percent_increase: 0 },
    { id: 235, code: "UZ", name_en: "UZBEKISTAN", name_th: "ประเทศอุซเบกิสถาน", type: "B", percent_increase: 0 },
    { id: 236, code: "VA", name_en: "VATICAN CITY", name_th: "นครรัฐวาติกัน", type: null, percent_increase: 0 },
    { id: 237, code: "VC", name_en: "SAINT VINCENT AND THE GRENADINES", name_th: "ประเทศเซนต์วินเซนต์และเกรนาดีนส์", type: null, percent_increase: 0 },
    { id: 238, code: "VE", name_en: "VENEZUELA", name_th: "ประเทศเวเนซุเอลา", type: null, percent_increase: 0 },
    { id: 239, code: "VG", name_en: "VIRGIN ISLANDS (BRITISH)", name_th: "ประเทศหมู่เกาะบริติชเวอร์จิน", type: null, percent_increase: 0 },
    { id: 240, code: "VI", name_en: "VIRGIN ISLANDS (U.S.)", name_th: "ประเทศหมู่เกาะเวอร์จินของสหรัฐอเมริกา", type: null, percent_increase: 0 },
    { id: 241, code: "VN", name_en: "VIETNAM", name_th: "ประเทศเวียดนาม", type: "B", percent_increase: 0 },
    { id: 242, code: "VU", name_en: "VANUATU", name_th: "ประเทศวานูวาตู", type: null, percent_increase: 0 },
    { id: 243, code: "WF", name_en: "WALLIS AND FUTUNA ISLANDS", name_th: "ประเทศวาลิสและฟูตูนา", type: null, percent_increase: 0 },
    { id: 244, code: "WS", name_en: "SAMOA", name_th: "ประเทศซามัว", type: null, percent_increase: 0 },
    { id: 245, code: "YE", name_en: "YEMEN", name_th: "ประเทศเยเมน", type: "B", percent_increase: 0 },
    { id: 246, code: "YT", name_en: "MAYOTTE", name_th: "ประเทศมายอต", type: null, percent_increase: 0 },
    { id: 247, code: "YY", name_en: "FOR HIGH SEA ZONE", name_th: "ประเทศน่านน้ำสากล", type: null, percent_increase: 0 },
    { id: 248, code: "ZA", name_en: "SOUTH AFRICA", name_th: "ประเทศแอฟริกาใต้", type: "A", percent_increase: 0 },
    { id: 249, code: "ZM", name_en: "ZAMBIA", name_th: "ประเทศแซมเบีย", type: "B", percent_increase: 0 },
    { id: 250, code: "ZR", name_en: "ZAIRE", name_th: "สาธารณรัฐซาอีร์", type: null, percent_increase: 0 },
    { id: 251, code: "ZW", name_en: "ZIMBABWE", name_th: "ประเทศซิมบับเว", type: "B", percent_increase: 0 }
    ];
    
    module.exports = countries;