const countries = [
  { id: 1, code: "AD", name_en: "ANDORRA", name_th: "อันดอร์รา" },
  { id: 2, code: "AE", name_en: "UNITED ARAB EMIRATES", name_th: "สหรัฐอาหรับเอมิเรตส์" },
  { id: 3, code: "AF", name_en: "AFGHANISTAN", name_th: "อัฟกานิสถาน" },
  { id: 4, code: "AG", name_en: "ANTIGUA AND BARBUDA", name_th: "แอนติกาและบาร์บูดา" },
  { id: 5, code: "AI", name_en: "ANGUILLA", name_th: "แองกวิลลา" },
  { id: 6, code: "AL", name_en: "ALBANIA", name_th: "แอลเบเนีย" },
  { id: 7, code: "AM", name_en: "ARMENIA", name_th: "อาร์มีเนีย" },
  { id: 8, code: "AO", name_en: "ANGOLA", name_th: "แองโกลา" },
  { id: 9, code: "AQ", name_en: "ANTARCTICA", name_th: "แอนตาร์กติกา" },
  { id: 10, code: "AR", name_en: "ARGENTINA", name_th: "อาร์เจนตินา" },
  { id: 11, code: "AS", name_en: "AMERICAN SAMOA", name_th: "อเมริกันซามัว" },
  { id: 12, code: "AT", name_en: "AUSTRIA", name_th: "ออสเตรีย" },
  { id: 13, code: "AU", name_en: "AUSTRALIA", name_th: "ออสเตรเลีย" },
  { id: 14, code: "AW", name_en: "ARUBA", name_th: "อารูบา" },
  { id: 15, code: "AX", name_en: "ALAND ISLANDS", name_th: "หมู่เกาะโอลันด์" },
  { id: 16, code: "AZ", name_en: "AZERBAIJAN", name_th: "อาเซอร์ไบจาน" },
  { id: 17, code: "BA", name_en: "BOSNIA AND HERZEGOVINA", name_th: "บอสเนียและเฮอร์เซโกวีนา" },
  { id: 18, code: "BB", name_en: "BARBADOS", name_th: "บาร์เบโดส" },
  { id: 19, code: "BD", name_en: "BANGLADESH", name_th: "บังกลาเทศ" },
  { id: 20, code: "BE", name_en: "BELGIUM", name_th: "เบลเยียม" },
  { id: 21, code: "BF", name_en: "BURKINA FASO", name_th: "บูร์กินาฟาโซ" },
  { id: 22, code: "BG", name_en: "BULGARIA", name_th: "บัลแกเรีย" },
  { id: 23, code: "BH", name_en: "BAHRAIN", name_th: "บาห์เรน" },
  { id: 24, code: "BI", name_en: "BURUNDI", name_th: "บุรุนดี" },
  { id: 25, code: "BJ", name_en: "BENIN", name_th: "เบนิน" },
  { id: 26, code: "BL", name_en: "SAINT BARTHELEMY", name_th: "แซงบาร์เตเลมี" },
  { id: 27, code: "BM", name_en: "BERMUDA", name_th: "เบอร์มิวดา" },
  { id: 28, code: "BN", name_en: "BRUNEI DARUSSALAM", name_th: "บรูไน" },
  { id: 29, code: "BO", name_en: "BOLIVIA", name_th: "โบลิเวีย" },
  { id: 30, code: "BQ", name_en: "BONAIRE,SAINT EUSTATIUS AND SABA", name_th: "เนเธอร์แลนด์แคริบเบียน" },
  { id: 31, code: "BR", name_en: "BRAZIL", name_th: "บราซิล" },
  { id: 32, code: "BS", name_en: "BAHAMAS", name_th: "บาฮามาส" },
  { id: 33, code: "BT", name_en: "BHUTAN", name_th: "ภูฏาน" },
  { id: 34, code: "BV", name_en: "BOUVET ISLAND", name_th: "เกาะบูเวต์" },
  { id: 35, code: "BW", name_en: "BOTSWANA", name_th: "บอตสวานา" },
  { id: 36, code: "BY", name_en: "BELARUS", name_th: "เบลารุส" },
  { id: 37, code: "BZ", name_en: "BELIZE", name_th: "เบลีซ" },
  { id: 38, code: "CA", name_en: "CANADA", name_th: "แคนาดา" },
  { id: 39, code: "CC", name_en: "COCOS (KEELING) ISLANDS", name_th: "หมู่เกาะโคโคส" },
  { id: 40, code: "CD", name_en: "CONGO, THE DEMOCRATIC REPUBLIC OF T", name_th: "สาธารณรัฐประชาธิปไตยคองโก" },
  { id: 41, code: "CF", name_en: "CENTRAL AFRICAN REPUBLIC", name_th: "สาธารณรัฐแอฟริกากลาง" },
  { id: 42, code: "CG", name_en: "CONGO", name_th: "สาธารณรัฐคองโก" },
  { id: 43, code: "CH", name_en: "SWITZERLAND", name_th: "สวิตเซอร์แลนด์" },
  { id: 44, code: "CI", name_en: "COTE D IVOIRE", name_th: "โกตดิวัวร์" },
  { id: 45, code: "CK", name_en: "COOK ISLANDS", name_th: "หมู่เกาะคุก" },
  { id: 46, code: "CL", name_en: "CHILE", name_th: "ชิลี" },
  { id: 47, code: "CM", name_en: "CAMEROON", name_th: "แคเมอรูน" },
  { id: 48, code: "CN", name_en: "CHINA", name_th: "จีน" },
  { id: 49, code: "CO", name_en: "COLOMBIA", name_th: "โคลอมเบีย" },
  { id: 50, code: "CR", name_en: "COSTA RICA", name_th: "คอสตาริกา" },
  { id: 51, code: "CU", name_en: "CUBA", name_th: "คิวบา" },
  { id: 52, code: "CV", name_en: "CAPE VERDE", name_th: "กาบูเวร์ดี" },
  { id: 53, code: "CW", name_en: "CURACAO", name_th: "กือราเซา" },
  { id: 54, code: "CX", name_en: "CHRISTMAS ISLAND", name_th: "เกาะคริสต์มาส" },
  { id: 55, code: "CY", name_en: "CYPRUS", name_th: "ไซปรัส" },
  { id: 56, code: "CZ", name_en: "CZECH REPUBLIC", name_th: "เช็กเกีย" },
  { id: 57, code: "DE", name_en: "GERMANY", name_th: "เยอรมนี" },
  { id: 58, code: "DJ", name_en: "DJIBOUTI", name_th: "จิบูตี" },
  { id: 59, code: "DK", name_en: "DENMARK", name_th: "เดนมาร์ก" },
  { id: 60, code: "DM", name_en: "DOMINICA", name_th: "ดอมินีกา" },
  { id: 61, code: "DO", name_en: "DOMINICAN REPUBLIC", name_th: "สาธารณรัฐโดมินิกัน" },
  { id: 62, code: "DZ", name_en: "ALGERIA", name_th: "แอลจีเรีย" },
  { id: 63, code: "EC", name_en: "ECUADOR", name_th: "เอกวาดอร์" },
  { id: 64, code: "EE", name_en: "ESTONIA", name_th: "เอสโตเนีย" },
  { id: 65, code: "EG", name_en: "EGYPT", name_th: "อียิปต์" },
  { id: 66, code: "EH", name_en: "WESTERN SAHARA", name_th: "ซาฮาราตะวันตก" },
  { id: 67, code: "ER", name_en: "ERITREA", name_th: "เอริเทรีย" },
  { id: 68, code: "ES", name_en: "SPAIN", name_th: "สเปน" },
  { id: 69, code: "ET", name_en: "ETHIOPIA", name_th: "เอธิโอเปีย" },
  { id: 70, code: "FI", name_en: "FINLAND", name_th: "ฟินแลนด์" },
  { id: 71, code: "FJ", name_en: "FIJI", name_th: "ฟีจี" },
  { id: 72, code: "FK", name_en: "FALKLAND ISLANDS (MALVINAS)", name_th: "หมู่เกาะฟอล์กแลนด์" },
  { id: 73, code: "FM", name_en: "MICRONESIA (FEDERATED STATES OF)", name_th: "ไมโครนีเซีย" },
  { id: 74, code: "FO", name_en: "FAROE ISLANDS", name_th: "หมู่เกาะแฟโร" },
  { id: 75, code: "FR", name_en: "FRANCE", name_th: "ฝรั่งเศส" },
  { id: 76, code: "GA", name_en: "GABON", name_th: "กาบอง" },
  { id: 77, code: "GB", name_en: "UNITED KINGDOM", name_th: "สหราชอาณาจักร" },
  { id: 78, code: "GD", name_en: "GRENADA", name_th: "เกรเนดา" },
  { id: 79, code: "GE", name_en: "GEORGIA", name_th: "จอร์เจีย" },
  { id: 80, code: "GF", name_en: "FRENCE GUIANA", name_th: "เฟรนช์เกียนา" },
  { id: 81, code: "GG", name_en: "GUERNSEY", name_th: "เกิร์นซีย์" },
  { id: 82, code: "GH", name_en: "GHANA", name_th: "กานา" },
  { id: 83, code: "GI", name_en: "GIBRALTAR", name_th: "ยิบรอลตาร์" },
  { id: 84, code: "GL", name_en: "GREENLAND", name_th: "กรีนแลนด์" },
  { id: 85, code: "GM", name_en: "GAMBIA", name_th: "แกมเบีย" },
  { id: 86, code: "GN", name_en: "GUINEA", name_th: "กินี" },
  { id: 87, code: "GP", name_en: "GUADELOUPE", name_th: "กัวเดอลุป" },
  { id: 88, code: "GQ", name_en: "EQUATORIAL GUINEA", name_th: "อิเควทอเรียลกินี" },
  { id: 89, code: "GR", name_en: "GREECE", name_th: "กรีซ" },
  { id: 90, code: "GS", name_en: "SOUTH GEORGIA AND THE SOUTH SANDWIC", name_th: "เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช" },
  { id: 91, code: "GT", name_en: "GUATEMALA", name_th: "กัวเตมาลา" },
  { id: 92, code: "GU", name_en: "GUAM", name_th: "กวม" },
  { id: 93, code: "GW", name_en: "GUINEA-BISSAU", name_th: "กินี-บิสเซา" },
  { id: 94, code: "GY", name_en: "GUYANA", name_th: "กายอานา" },
  { id: 95, code: "HK", name_en: "HONG KONG", name_th: "ฮ่องกง" },
  { id: 96, code: "HM", name_en: "HEARD ISLAND AND MCDONALD ISLANDS", name_th: "เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์" },
  { id: 97, code: "HN", name_en: "HONDURAS", name_th: "ฮอนดูรัส" },
  { id: 98, code: "HR", name_en: "CROATIA", name_th: "โครเอเชีย" },
  { id: 99, code: "HT", name_en: "HAITI", name_th: "เฮติ" },
  { id: 100, code: "HU", name_en: "HUNGARY", name_th: "ฮังการี" },
  { id: 101, code: "ID", name_en: "INDONESIA", name_th: "อินโดนีเซีย" },
  { id: 102, code: "IE", name_en: "IRELAND", name_th: "ไอร์แลนด์" },
  { id: 103, code: "IL", name_en: "ISRAEL", name_th: "อิสราเอล" },
  { id: 104, code: "IM", name_en: "ISLE OF MAN", name_th: "ไอล์ออฟแมน" },
  { id: 105, code: "IN", name_en: "INDIA", name_th: "อินเดีย" },
  { id: 106, code: "IO", name_en: "BRITISH INDIAN OCEAN TERRITORY", name_th: "บริติชอินเดียนโอเชียนเทร์ริทอรี" },
  { id: 107, code: "IQ", name_en: "IRAQ", name_th: "อิรัก" },
  { id: 108, code: "IR", name_en: "IRAN (ISLAMIC REPUBLIC OF)", name_th: "อิหร่าน" },
  { id: 109, code: "IS", name_en: "ICELAND", name_th: "ไอซ์แลนด์" },
  { id: 110, code: "IT", name_en: "ITALY", name_th: "อิตาลี" },
  { id: 111, code: "JE", name_en: "JERSEY", name_th: "เจอร์ซีย์" },
  { id: 112, code: "JM", name_en: "JAMAICA", name_th: "จาเมกา" },
  { id: 113, code: "JO", name_en: "JORDAN", name_th: "จอร์แดน" },
  { id: 114, code: "JP", name_en: "JAPAN", name_th: "ญี่ปุ่น" },
  { id: 115, code: "KE", name_en: "KENYA", name_th: "เคนยา" },
  { id: 116, code: "KG", name_en: "KYRGYZSTAN", name_th: "คีร์กีซสถาน" },
  { id: 117, code: "KH", name_en: "CAMBODIA", name_th: "กัมพูชา" },
  { id: 118, code: "KI", name_en: "KIRIBATI", name_th: "คิริบาส" },
  { id: 119, code: "KM", name_en: "COMOROS", name_th: "คอโมโรส" },
  { id: 120, code: "KN", name_en: "SAINT KITTS AND NEVIS", name_th: "เซนต์คิตส์และเนวิส" },
  { id: 121, code: "KP", name_en: "KOREA DPR", name_th: "เกาหลีเหนือ" },
  { id: 122, code: "KR", name_en: "KOREA,REPUBLIC OF", name_th: "เกาหลีใต้" },
  { id: 123, code: "KW", name_en: "KUWAIT", name_th: "คูเวต" },
  { id: 124, code: "KY", name_en: "CAYMAN ISLANDS", name_th: "หมู่เกาะเคย์แมน" },
  { id: 125, code: "KZ", name_en: "KAZAKHSTAN", name_th: "คาซัคสถาน" },
  { id: 126, code: "LA", name_en: "LAO PDR", name_th: "ลาว" },
  { id: 127, code: "LB", name_en: "LEBANON", name_th: "เลบานอน" },
  { id: 128, code: "LC", name_en: "SAINT LUCIA", name_th: "เซนต์ลูเชีย" },
  { id: 129, code: "LI", name_en: "LIECHTENSTEIN", name_th: "ลิกเตนสไตน์" },
  { id: 130, code: "LK", name_en: "SRI LANKA", name_th: "ศรีลังกา" },
  { id: 131, code: "LR", name_en: "LIBERIA", name_th: "ไลบีเรีย" },
  { id: 132, code: "LS", name_en: "LESOTHO", name_th: "เลโซโท" },
  { id: 133, code: "LT", name_en: "LITHUANIA", name_th: "ลิทัวเนีย" },
  { id: 134, code: "LU", name_en: "LUXEMBOURG", name_th: "ลักเซมเบิร์ก" },
  { id: 135, code: "LV", name_en: "LATVIA", name_th: "ลัตเวีย" },
  { id: 136, code: "LY", name_en: "LIBYAN ARAB JAMAHIRIYA", name_th: "ลิเบีย" },
  { id: 137, code: "MA", name_en: "MOROCCO", name_th: "โมร็อกโก" },
  { id: 138, code: "MC", name_en: "MONACO", name_th: "โมนาโก" },
  { id: 139, code: "MD", name_en: "MOLDOVA REPUBLIC OF", name_th: "มอลโดวา" },
  { id: 140, code: "ME", name_en: "MONTENEGRO", name_th: "มอนเตเนโกร" },
  { id: 141, code: "MF", name_en: "SAINT MARTIN (FRENCH PART)", name_th: "แซงมาร์แตง" },
  { id: 142, code: "MG", name_en: "MADAGASCAR", name_th: "มาดากัสการ์" },
  { id: 143, code: "MH", name_en: "MARSHALL ISLAND", name_th: "หมู่เกาะมาร์แชลล์" },
  { id: 144, code: "MK", name_en: "THE REPUBLIC OF NORTH MACEDONIA", name_th: "นอร์ทมาซิโดเนีย" },
  { id: 145, code: "ML", name_en: "MALI", name_th: "มาลี" },
  { id: 146, code: "MM", name_en: "MYANMAR", name_th: "พม่า" },
  { id: 147, code: "MN", name_en: "MONGOLIA", name_th: "มองโกเลีย" },
  { id: 148, code: "MO", name_en: "MACAU", name_th: "มาเก๊า" },
  { id: 149, code: "MP", name_en: "NORTHERN MARIANA ISLANDS", name_th: "หมู่เกาะนอร์เทิร์นมาเรียนา" },
  { id: 150, code: "MQ", name_en: "MARTINIQUE", name_th: "มาร์ตีนิก" },
  { id: 151, code: "MR", name_en: "MAURITANIA", name_th: "มอริเตเนีย" },
  { id: 152, code: "MS", name_en: "MONTSERRAT", name_th: "มอนต์เซอร์รัต" },
  { id: 153, code: "MT", name_en: "MALTA", name_th: "มอลตา" },
  { id: 154, code: "MU", name_en: "MAURITIUS", name_th: "มอริเชียส" },
  { id: 155, code: "MV", name_en: "MALDIVES", name_th: "มัลดีฟส์" },
  { id: 156, code: "MW", name_en: "MALAWI", name_th: "มาลาวี" },
  { id: 157, code: "MX", name_en: "MEXICO", name_th: "เม็กซิโก" },
  { id: 158, code: "MY", name_en: "MALAYSIA", name_th: "มาเลเซีย" },
  { id: 159, code: "MZ", name_en: "MOZAMBIQUE", name_th: "โมซัมบิก" },
  { id: 160, code: "NA", name_en: "NAMIBIA", name_th: "นามิเบีย" },
  { id: 161, code: "NC", name_en: "NEW CALEDONIA", name_th: "นิวแคลิโดเนีย" },
  { id: 162, code: "NE", name_en: "NIGER", name_th: "ไนเจอร์" },
  { id: 163, code: "NF", name_en: "NORFOLK ISLAND", name_th: "เกาะนอร์ฟอล์ก" },
  { id: 164, code: "NG", name_en: "NIGERIA", name_th: "ไนจีเรีย" },
  { id: 165, code: "NI", name_en: "NICARAGUA", name_th: "นิการากัว" },
  { id: 166, code: "NL", name_en: "NETHERLANDS", name_th: "เนเธอร์แลนด์" },
  { id: 167, code: "NO", name_en: "NORWAY", name_th: "นอร์เวย์" },
  { id: 168, code: "NP", name_en: "NEPAL", name_th: "เนปาล" },
  { id: 169, code: "NR", name_en: "NAURU", name_th: "นาอูรู" },
  { id: 170, code: "NU", name_en: "NIUE", name_th: "นีวเว" },
  { id: 171, code: "NZ", name_en: "NEW ZEALAND", name_th: "นิวซีแลนด์" },
  { id: 172, code: "OM", name_en: "OMAN", name_th: "โอมาน" },
  { id: 173, code: "PA", name_en: "PANAMA", name_th: "ปานามา" },
  { id: 174, code: "PE", name_en: "PERU", name_th: "เปรู" },
  { id: 175, code: "PF", name_en: "FRENCH POLYNESIA", name_th: "เฟรนช์พอลินีเชีย" },
  { id: 176, code: "PG", name_en: "PAPUA NEW GUINEA", name_th: "ปาปัวนิวกินี" },
  { id: 177, code: "PH", name_en: "PHILIPPINES", name_th: "ฟิลิปปินส์" },
  { id: 178, code: "PK", name_en: "PAKISTAN", name_th: "ปากีสถาน" },
  { id: 179, code: "PL", name_en: "POLAND", name_th: "โปแลนด์" },
  { id: 180, code: "PM", name_en: "SAINT PIERRE AND MIQUELON", name_th: "แซงปีแยร์และมีเกอลง" },
  { id: 181, code: "PN", name_en: "PITCAIRN", name_th: "หมู่เกาะพิตแคร์น" },
  { id: 182, code: "PR", name_en: "PUERTO RICO", name_th: "ปวยร์โตรีโก" },
  { id: 183, code: "PS", name_en: "PALESTINIAN TERRITORY, OCCUPIED", name_th: "ปาเลสไตน์" },
  { id: 184, code: "PT", name_en: "PORTUGAL", name_th: "โปรตุเกส" },
  { id: 185, code: "PW", name_en: "PALAU", name_th: "ปาเลา" },
  { id: 186, code: "PY", name_en: "PARAGUAY", name_th: "ปารากวัย" },
  { id: 187, code: "QA", name_en: "QATAR", name_th: "กาตาร์" },
  { id: 188, code: "RE", name_en: "REUNION", name_th: "เรอูว์นียง" },
  { id: 189, code: "RO", name_en: "ROMANIA", name_th: "โรมาเนีย" },
  { id: 190, code: "RS", name_en: "SERBIA", name_th: "เซอร์เบีย" },
  { id: 191, code: "RU", name_en: "RUSSIAN FEDERATION", name_th: "รัสเซีย" },
  { id: 192, code: "RW", name_en: "RWANDA", name_th: "รวันดา" },
  { id: 193, code: "SA", name_en: "SAUDI ARABIA", name_th: "ซาอุดีอาระเบีย" },
  { id: 194, code: "SB", name_en: "SOLOMON ISLANDS", name_th: "หมู่เกาะโซโลมอน" },
  { id: 195, code: "SC", name_en: "SEYCHELLES", name_th: "เซเชลส์" },
  { id: 196, code: "SD", name_en: "SUDAN", name_th: "ซูดาน" },
  { id: 197, code: "SE", name_en: "SWEDEN", name_th: "สวีเดน" },
  { id: 198, code: "SG", name_en: "SINGAPORE", name_th: "สิงคโปร์" },
  { id: 199, code: "SH", name_en: "SAINT HELENA", name_th: "เซนต์เฮเลนา" },
  { id: 200, code: "SI", name_en: "SLOVENIA", name_th: "สโลวีเนีย" },
  { id: 201, code: "SJ", name_en: "SVALBARD AND JAN MAYEN", name_th: "สฟาลบาร์และยานไมเอน" },
  { id: 202, code: "SK", name_en: "SLOVAKIA", name_th: "สโลวาเกีย" },
  { id: 203, code: "SL", name_en: "SIERRA LEONE", name_th: "เซียร์ราลีโอน" },
  { id: 204, code: "SM", name_en: "SAN MARINO", name_th: "ซานมารีโน" },
  { id: 205, code: "SN", name_en: "SENEGAL", name_th: "เซเนกัล" },
  { id: 206, code: "SO", name_en: "SOMALIA", name_th: "โซมาเลีย" },
  { id: 207, code: "SR", name_en: "SURINAME", name_th: "ซูรินาม" },
  { id: 208, code: "SS", name_en: "SOUTH SUDAN", name_th: "เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช" },
  { id: 209, code: "ST", name_en: "SAO TOME AND PRINCIPE", name_th: "เซาตูเมและปรินซีปี" },
  { id: 210, code: "SV", name_en: "EL SALVADOR", name_th: "เอลซัลวาดอร์" },
  { id: 211, code: "SX", name_en: "SINT MAARTEN", name_th: "ซินต์มาร์เติน" },
  { id: 212, code: "SY", name_en: "SYRIAN ARAB REPUBLIC", name_th: "ซีเรีย" },
  { id: 213, code: "SZ", name_en: "ESWATINI", name_th: "สวาซิแลนด์" },
  { id: 214, code: "TC", name_en: "TURKS AND CAICOS ISLANDS", name_th: "หมู่เกาะเติกส์และเคคอส" },
  { id: 215, code: "TD", name_en: "CHAD", name_th: "ชาด" },
  { id: 216, code: "TF", name_en: "FRENCH SOUTHERN TERRITORIES", name_th: "เฟรนช์เซาเทิร์นและแอนตาร์กติกแลนดส์" },
  { id: 217, code: "TG", name_en: "TOGO", name_th: "โตโก" },
  { id: 218, code: "TH", name_en: "THAILAND", name_th: "ไทย" },
  { id: 219, code: "TJ", name_en: "TAJIKISTAN", name_th: "ทาจิกิสถาน" },
  { id: 220, code: "TK", name_en: "TOKELAU", name_th: "โทเคอเลา" },
  { id: 221, code: "TL", name_en: "TIMOR-LESTE", name_th: "ติมอร์-เลสเต" },
  { id: 222, code: "TM", name_en: "TURKMENISTAN", name_th: "เติร์กเมนิสถาน" },
  { id: 223, code: "TN", name_en: "TUNISIA", name_th: "ตูนิเซีย" },
  { id: 224, code: "TO", name_en: "TONGA", name_th: "ตองงา" },
  { id: 225, code: "TR", name_en: "TURKIYE", name_th: "ตุรกี" },
  { id: 226, code: "TT", name_en: "TRINIDAD AND TOBAGO", name_th: "ตรินิแดดและโตเบโก" },
  { id: 227, code: "TV", name_en: "TUVALU", name_th: "ตูวาลู" },
  { id: 228, code: "TW", name_en: "TAIWAN, PROVINCE OF CHINA", name_th: "ไต้หวัน" },
  { id: 229, code: "TZ", name_en: "TANZANIA UNITED REPUBLIC OF", name_th: "แทนซาเนีย" },
  { id: 230, code: "UA", name_en: "UKRAINE", name_th: "ยูเครน" },
  { id: 231, code: "UG", name_en: "UGANDA", name_th: "ยูกันดา" },
  { id: 232, code: "UM", name_en: "UNITED STATES MINOR OUTLYING ISLAND", name_th: "เกาะเล็กรอบนอกของสหรัฐอเมริกา" },
  { id: 233, code: "US", name_en: "UNITED STATES", name_th: "สหรัฐ" },
  { id: 234, code: "UY", name_en: "URUGUAY", name_th: "อุรุกวัย" },
  { id: 235, code: "UZ", name_en: "UZBEKISTAN", name_th: "อุซเบกิสถาน" },
  { id: 236, code: "VA", name_en: "VATICAN CITY", name_th: "นครรัฐวาติกัน" },
  { id: 237, code: "VC", name_en: "SAINT VINCENT AND THE GRENADINES", name_th: "เซนต์วินเซนต์และเกรนาดีนส์" },
  { id: 238, code: "VE", name_en: "VENEZUELA", name_th: "เวเนซุเอลา" },
  { id: 239, code: "VG", name_en: "VIRGIN ISLANDS (BRITISH)", name_th: "หมู่เกาะบริติชเวอร์จิน" },
  { id: 240, code: "VI", name_en: "VIRGIN ISLANDS (U.S.)", name_th: "หมู่เกาะเวอร์จินของสหรัฐอเมริกา" },
  { id: 241, code: "VN", name_en: "VIETNAM", name_th: "เวียดนาม" },
  { id: 242, code: "VU", name_en: "VANUATU", name_th: "วานูวาตู" },
  { id: 243, code: "WF", name_en: "WALLIS AND FUTUNA ISLANDS", name_th: "วาลิสและฟูตูนา" },
  { id: 244, code: "WS", name_en: "SAMOA", name_th: "ซามัว" },
  { id: 245, code: "YE", name_en: "YEMEN", name_th: "เยเมน" },
  { id: 246, code: "YT", name_en: "MAYOTTE", name_th: "มายอต" },
  { id: 247, code: "YY", name_en: "FOR HIGH SEA ZONE", name_th: "น่านน้ำสากล" },
  { id: 248, code: "ZA", name_en: "SOUTH AFRICA", name_th: "แอฟริกาใต้" },
  { id: 249, code: "ZM", name_en: "ZAMBIA", name_th: "แซมเบีย" },
  { id: 250, code: "ZR", name_en: "ZAIRE", name_th: "สาธารณรัฐซาอีร์" },
  { id: 251, code: "ZW", name_en: "ZIMBABWE", name_th: "ซิมบับเว" }
];

module.exports = countries; 