module.exports = {
  currency: [
    {
      id: 1,
      currency_th: 'บาทประเทศไทย',
      currency_code_th: 'บาท',
      currency_en: 'Thai Baht',
      currency_code_en: 'THB',
    },
    {
      id: 2,
      currency_th: 'ดอลลาร์สหรัฐ',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'US Dollar',
      currency_code_en: 'USD',
    },
    {
      id: 3,
      currency_th: 'ดอลลาร์สิงคโปร์',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'Singapore Dollar',
      currency_code_en: 'SGD',
    },
    {
      id: 4,
      currency_th: 'ดอลลาร์ฮ่องกง',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'Hong Kong Dollar',
      currency_code_en: 'HKD',
    },
    {
      id: 5,
      currency_th: 'ปอนด์สเตอร์ลิง',
      currency_code_th: 'สเตอร์ลิง',
      currency_en: 'Pound Sterling',
      currency_code_en: 'GBP',
    },
    {
      id: 6,
      currency_th: 'โครนสวีเดน',
      currency_code_th: 'โครน',
      currency_en: 'Swedish Krona',
      currency_code_en: 'SEK',
    },
    {
      id: 7,
      currency_th: 'ดอลลาร์ออสเตรเลีย',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'Australian Dollar',
      currency_code_en: 'AUD',
    },
    {
      id: 8,
      currency_th: 'เยนญี่ปุ่น',
      currency_code_th: 'เยน',
      currency_en: 'Japanese Yen',
      currency_code_en: 'JPY',
    },
    {
      id: 9,
      currency_th: 'ปอนด์',
      currency_code_th: 'ปอนด์',
      currency_en: 'Pound',
      currency_code_en: 'GBP',
    },
    {
      id: 10,
      currency_th: 'ยูโร',
      currency_code_th: 'ยูโร',
      currency_en: 'Euro',
      currency_code_en: 'EUR',
    },
    {
      id: 11,
      currency_th: 'โครูนเช็ก',
      currency_code_th: 'โคลน',
      currency_en: 'Czech Koruna',
      currency_code_en: 'CZK',
    },
    {
      id: 12,
      currency_th: 'ดอลลาร์แคนาดา',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'Canadian Dollar',
      currency_code_en: 'CAD',
    },
    {
      id: 13,
      currency_th: 'โครนนอร์เวย์',
      currency_code_th: 'โครน',
      currency_en: 'Norwegian Krone',
      currency_code_en: 'NOK',
    },
    {
      id: 14,
      currency_th: 'ดอลลาร์นิวซีแลนด์',
      currency_code_th: 'ดอลลาร์',
      currency_en: 'New Zealand Dollar',
      currency_code_en: 'NZD',
    },
    {
      id: 15,
      currency_th: 'ฟรังก์สวิส',
      currency_code_th: 'ฟรังก์',
      currency_en: 'Swiss Franc',
      currency_code_en: 'CHF',
    },
  ],
};
