/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
  return knex('menu_items_access').insert([
    {
      key_name: 'dashboard',
      title: 'หน้าแรก',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-system',
      title: '1. ระบบขออนุมัติเดินทาง',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval',
      title: 'ขออนุมัติเดินทาง',
      parent_key: 'approval-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-add',
      title: 'เพิ่มรายการขออนุมัติ',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-draft',
      title: 'รายการขออนุมัติฉบับร่าง',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-pending',
      title: 'รายการรออนุมัติ',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-rejected',
      title: 'รายการถูกปฏิเสธ',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-approved',
      title: 'รายการที่ได้รับอนุมัติ',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-to-approve',
      title: 'รายการที่ฉันต้องอนุมัติ',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'approval-related',
      title: 'รายการที่เกี่ยวข้องกับฉัน',
      parent_key: 'approval',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'reports-system',
      title: '2. ระบบรายงานการเดินทาง',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'commute-reports',
      title: 'รายงานการเดินทาง',
      parent_key: 'reports-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'commute-create',
      title: 'สร้างรายงานการเดินทางใหม่',
      parent_key: 'commute-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'commute-approve',
      title: 'สร้างรายงานจากอนมุัติเดินทาง',
      parent_key: 'commute-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'commute-all',
      title: 'รายงานการเดินทางทั้งหมด',
      parent_key: 'commute-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'certificate-reports',
      title: 'ใบรับรองแทนใบเสร็จ',
      parent_key: 'reports-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'certificate-create',
      title: 'สร้างใบรับรองแทนใบเสร็จ',
      parent_key: 'certificate-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'certificate-all',
      title: 'ใบรับรองแทนใบเสร็จทั้งหมด',
      parent_key: 'certificate-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'entertainment-reports',
      title: 'ฟอร์มเบิกจ่ายค่าเลี้ยงรับรอง',
      parent_key: 'reports-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'entertainment-create',
      title: 'สร้างฟอร์มเบิกจ่ายค่าเลี้ยงรับรอง',
      parent_key: 'entertainment-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'entertainment-all',
      title: 'ฟอร์มเบิกจ่ายค่าเลี้ยงรับรองทั้งหมด',
      parent_key: 'entertainment-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'meet-reports',
      title: 'ฟอร์มเบิกจ่ายค่าจัดประชุม',
      parent_key: 'reports-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'meet-create',
      title: 'สร้างฟอร์มเบิกจ่ายค่าจัดประชุม',
      parent_key: 'meet-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'meet-all',
      title: 'ฟอร์มเบิกจ่ายค่าจัดประชุมทั้งหมด',
      parent_key: 'meet-reports',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'disbursement-system',
      title: '3. เอกสารประกอบเบิกจ่าย',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'disbursement-documents',
      title: 'เอกสารประกอบการเบิกจ่าย',
      parent_key: 'disbursement-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'forms-system',
      title: '4. แบบฟอร์มและเอกสารอื่นๆ',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'forms-list',
      title: 'แบบฟอร์มและเอกสารอื่นๆ',
      parent_key: 'forms-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'clothing-system',
      title: '5. การเบิกค่าเครื่องแต่งกาย',
      parent_key: null,
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'clothing',
      title: 'การเบิกค่าเครื่องแต่งกาย',
      parent_key: 'clothing-system',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'clothing-list',
      title: 'รายการเบิกค่าเครื่องแต่งกาย',
      parent_key: 'clothing',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'clothing-pending',
      title: 'รายการรอตรวจสอบขอยกเลิก',
      parent_key: 'clothing',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'clothing-history',
      title: 'ประวัติการเบิกค่าเครื่องแต่งกาย',
      parent_key: 'clothing',
      is_active: true,
      is_admin: false,
    },
    {
      key_name: 'admin-system',
      title: 'ส่วนสำหรับผู้ดูแลระบบ',
      parent_key: null,
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'admin-reports',
      title: 'รายงาน',
      parent_key: 'admin-system',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'master-data',
      title: 'Master Data',
      parent_key: 'admin-system',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'location-province',
      title: 'รายชื่อจังหวัด',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'location-amphur',
      title: 'รายชื่อเขต/อำเภอ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'location-place',
      title: 'รายชื่อสถานที่',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'location-country',
      title: 'รายชื่อประเทศ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'office-domestic',
      title: 'รายชื่อสำนักงาน ททท ในประเทศไทย',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'office-international',
      title: 'รายชื่อสำนักงาน ททท ต่างประเทศ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-other',
      title: 'รายการค่าใช้จ่ายอื่นๆ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-vehicle',
      title: 'ค่าพาหนะรับจ้าง',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-bangkok-to-place',
      title: 'ค่าพาหนะเขตกรุงเทพฯกับสถานที่',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-work-on-holiday',
      title: 'ค่าทำงานในวันหยุดและหักภาษี',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'employee-privilege',
      title: 'รายการสิทธิ์',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'currency',
      title: 'จัดการสกุลเงิน',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-entertainment',
      title: 'รายการค่าเลี้ยงรับรอง',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-per-diem-rate',
      title: 'รายการค่าเบี้ยเลี้ยงเดินทาง',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-accommodation-rate',
      title: 'รายการค่าที่พัก',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-domestic-moving',
      title: 'ระยะทางค่าขนย้ายประจำในประเทศ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-international-moving',
      title: 'ค่าพขต. ประจำในต่างประเทศ',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-attire-allowance',
      title: 'ค่าเครื่องแต่งกาย',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-attire-destination-groups',
      title: 'กลุ่มประเทศ (ค่าเครื่องแต่งกาย)',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'attire-allowance-history',
      title: 'ประวัติการเบิกค่าเครื่องแต่งตัว',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'expenses-entertainment-allowance',
      title: 'ค่ารับรองตามสิทธิ์',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'labels',
      title: 'ป้ายกำกับข้อมูลของ Master Data',
      parent_key: 'master-data',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'admin-users',
      title: 'จัดการสิทธิ์ผู้ดูแลระบบ',
      parent_key: 'admin-system',
      is_active: true,
      is_admin: true,
    },
    {
      key_name: 'admin-menu-items',
      title: 'จัดการรายการเมนู',
      parent_key: 'admin-system',
      is_active: true,
      is_admin: true,
    },
  ]);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
  return knex('menu_items_access').del();
};
