version: '3.8'

services:
  tat-api:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - LOG_MAX_FILES=30d
      - LOG_HTTP_MAX_FILES=14d
      - LOG_MAX_SIZE=20m
      - WS_PORT=8080
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    ports:
      - 3000:3000
      - 8080:8080
    command: npm run start:dev
    restart: unless-stopped
