version: '3.8'

services:
  tat-api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - LOG_MAX_FILES=30d
      - LOG_HTTP_MAX_FILES=14d
      - LOG_MAX_SIZE=20m
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    ports:
      - 8080:3000
    command: npm run start:dev
